# for backend

version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      # 登录 ECR
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 034362066948.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      # 编译
      - mvn install
      - echo npm install completed on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - mv ./target/shop-api-0.0.1-SNAPSHOT.jar ./target/app.jar
      - chmod 777 ./appstart.sh
artifacts:
  files:
    - target/app.jar
    - batch/*
    - appstart.sh
    - appspec.yml